version: '3.9'

services:
  flask:
    image: pollerapi
    container_name: flask
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5050:5050
    networks:
      - pollerapi-net
    volumes:
      - ./config.json:/app/config.json
    environment:
      - FLASK_APP=run.py

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - flask
    command: http flask:5050  # Expose Flask service through ngrok
    networks:
      - pollerapi-net
    environment:
      # If you have an ngrok authtoken, include it to avoid session time limits
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}  # Get it from https://dashboard.ngrok.com/get-started/your-authtoken
    ports:
      - 4040:4040  # Expose ngrok's web interface for inspection


networks:
  pollerapi-net:
    name: pollerapi-net